SERVER_IP = '10.14.11.252'
LOG = '/var/log/pimat-web.log'
UPLOAD_FOLDER = '/opt/pimat/pimat_web/static/images'
RELAY_CONFIG= '/opt/pimat/relays.ini'
SQLALCHEMY_DATABASE_URI = 'mysql://root:zaq12wsx@localhost/pimat'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = False
MAIL_SERVER = 'mail.ocloud.cz'
MAIL_PORT = 587
MAIL_USERNAME = 'teste@ocloud.cz'
MAIL_PASSWORD = 'zaq12wsx'
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_DEFAULT_SENDER = 'teste@ocloud.cz'
CSRF_ENABLED = True
RECAPTCHA = False
RECAPTCHA_PUBLIC_KEY = '6LcwqywUAAAAANqGKZdPMGUmBZ3nKwRadazZS2OZ'
RECAPTCHA_PRIVATE_KEY = '6LcwqywUAAAAAGB9HhvMq3C_JOfCYLBliH2-un7U'
SECRET_KEY = 'super secret string'
